# Enderpearl Cooldown Configuration (Default made by SirBlobman)
# Made for version ${project.version}

# Debug Mode is only necessary if you want to see extra information.
# SirBlobman may ask you to enable this option if you need help with an issue.
#
# Default: false
debug: false

# A list of worlds that will be ignored for Enderpearl Cooldown
#
# Default:
# - "None"
disabled worlds:
- "None"

# How should the cooldown timer be detected
# Possible Options:
# - NORMAL - All players have the same timer based on the config option
# - PERMISSION_BASED - Timer is based on permissions (enderpearl.cooldown.timer.<seconds>), if a permission can't be detected it will default to the config option
#
# Default: NORMAL
cooldown mode: NORMAL

# What is the default time for the cooldown?
# The timer is in seconds
#
# Default: 30
default timer: 30

# Players with this permission will only have the vanilla cooldown.
#
# Default: "enderpearl.cooldown.bypass"
bypass permission: "enderpearl.cooldown.bypass"

messages:
  in cooldown: "&cYou cannot use an ender pearl for &a{time_left}&e seconds."
  end cooldown: "&aYou can now use an ender pearl."
  action bar:
    timer: "&6&lEnderpearl Cooldown &7\u00BB &c{time_left} seconds."
    end timer: "&a&lReady!"